/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface': '#1a1c1c',
        'on-primary-container': '#fff2f3',
        'on-surface-variant': '#5a4044',
        'surface-container': '#eeeeee',
        'on-secondary-fixed': '#221b00',
        'surface-container-high': '#e8e8e8',
        'primary-fixed-dim': '#ffb2bf',
        'on-background': '#1a1c1c',
        'surface-container-highest': '#e2e2e2',
        'surface-bright': '#f9f9f9',
        'surface': '#f9f9f9',
        'on-primary-fixed-variant': '#90003b',
        'surface-tint': '#bc004f',
        'on-secondary': '#ffffff',
        'background': '#f9f9f9',
        'error-container': '#ffdad6',
        'tertiary': '#8d22a9',
        'primary': '#b0004a',
        'surface-variant': '#e2e2e2',
        'primary-fixed': '#ffd9de',
        'outline': '#8e6f74',
        'on-tertiary-fixed-variant': '#790096',
        'on-tertiary-fixed': '#340042',
        'primary-container': '#d81b60',
        'tertiary-fixed-dim': '#f3aeff',
        'on-error': '#ffffff',
        'on-primary-fixed': '#3f0016',
        'secondary-fixed-dim': '#e9c400',
        'surface-container-low': '#f3f3f3',
        'inverse-on-surface': '#f1f1f1',
        'secondary': '#705d00',
        'secondary-fixed': '#ffe16d',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#544600',
        'inverse-primary': '#ffb2bf',
        'tertiary-fixed': '#fdd6ff',
        'secondary-container': '#fcd400',
        'inverse-surface': '#2f3131',
        'error': '#ba1a1a',
        'on-error-container': '#93000a',
        'outline-variant': '#e3bdc3',
        'on-secondary-container': '#6e5c00',
        'surface-dim': '#dadada',
        'tertiary-container': '#a941c4',
        'on-primary': '#ffffff',
        'on-tertiary-container': '#fff1fc',
        'on-tertiary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '12px',
        base: '8px',
        md: '24px',
        lg: '40px',
        xl: '64px',
        gutter: '20px',
        'container-max': '1200px',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-xs': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Montserrat', 'sans-serif'],
        'headline-sm': ['Montserrat', 'sans-serif'],
        'headline-md': ['Montserrat', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Montserrat', 'sans-serif'],
        'headline-xl': ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-xs': ['10px', { lineHeight: '14px', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-sm-mobile': ['16px', { lineHeight: '22px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
